
import type { User, Experience, Conversation, ReviewData } from './types';

export const users: User[] = [
  { id: 'user-1', name: 'Ali Mohammed', avatar: 'https://placehold.co/100x100', aiHint: "man portrait", isHost: true },
  { id: 'user-2', name: 'Fatima Al-Asmari', avatar: 'https://placehold.co/100x100', aiHint: "woman portrait", isHost: true },
  { id: 'user-3', name: 'John Doe', avatar: 'https://placehold.co/100x100', aiHint: "tourist portrait", isHost: false },
  { id: 'user-4', name: 'Noura Khalid', avatar: 'https://placehold.co/100x100', aiHint: "host portrait", isHost: true },
  { id: 'user-5', name: 'Ibrahim Hassan', avatar: 'https://placehold.co/100x100', aiHint: "artisan portrait", isHost: true },
  { id: 'user-6', name: 'Layla Faisal', avatar: 'https://placehold.co/100x100', aiHint: "chef portrait", isHost: true },
];

const reviews: ReviewData[] = [
    { id: 'rev-1-1', user: users[2], rating: 5, comment: "Amazing experience! Fatima is a wonderful host and teacher.", date: '2023-10-15' },
    { id: 'rev-1-2', user: { id: 'user-7', name: 'Jane Smith', avatar: 'https://placehold.co/100x100', aiHint: 'tourist portrait', isHost: false }, rating: 5, comment: "A must-do in Abha. The food was incredible.", date: '2023-10-12' },
    { id: 'rev-2-1', user: users[2], rating: 5, comment: "Ibrahim is so talented and patient. A very meditative and rewarding workshop.", date: '2023-09-20' },
    { id: 'rev-3-1', user: users[2], rating: 5, comment: "The views were absolutely spectacular. Ali is very knowledgeable about the area.", date: '2023-10-05' },
];

export const experiences: Experience[] = [
  {
    id: 'exp-1',
    name: 'Traditional Asiri Cooking Class',
    description: 'Learn to cook authentic Asiri dishes in a local family home.',
    longDescription: 'Join Fatima in her family home for an immersive cooking experience. You will learn the secrets of traditional Asiri cuisine, from preparing the famous Aseedah to brewing the perfect Arabic coffee. This hands-on class uses fresh, local ingredients and ends with a communal meal where you can enjoy the fruits of your labor.',
    image: 'https://placehold.co/600x400',
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    aiHint: 'cooking class',
    host: users[1],
    location: 'Abha, Asir',
    price: 75,
    rating: 4.9,
    reviewsCount: 42,
    availability: 'Daily, 10am & 4pm',
    category: 'Food',
    whatYoullDo: ['Learn about local spices and ingredients', 'Prepare a 3-course Asiri meal', 'Enjoy the meal with the host family'],
    whatIsIncluded: ['All ingredients', 'Recipe book', 'Refreshments'],
    reviews: [reviews[0], reviews[1]]
  },
  {
    id: 'exp-2',
    name: 'Al-Qatt Al-Asiri Art Workshop',
    description: 'Discover the ancient art of Al-Qatt Al-Asiri with a master artisan.',
    longDescription: 'Under the guidance of Ibrahim, a master of the UNESCO-recognized Al-Qatt Al-Asiri art form, you will create your own masterpiece. This workshop covers the history of the art, the meaning behind the geometric patterns, and the techniques used to create these vibrant murals. You will leave with your own decorated wooden panel.',
    image: 'https://placehold.co/600x400',
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    aiHint: 'art workshop',
    host: users[4],
    location: 'Rijal Almaa',
    price: 90,
    rating: 4.8,
    reviewsCount: 35,
    availability: 'Mon, Wed, Fri at 2pm',
    category: 'Culture',
    whatYoullDo: ['Learn about the history and symbolism of Al-Qatt Al-Asiri', 'Practice drawing the traditional patterns', 'Paint your own decorative piece to take home'],
    whatIsIncluded: ['All art supplies', 'Wooden panel', 'Protective apron'],
     reviews: [reviews[2]]
  },
  {
    id: 'exp-3',
    name: 'Hiking Tour in the Juniper Forests',
    description: 'Explore the stunning landscapes and hidden villages of the Asir mountains.',
    longDescription: "Embark on a guided hike with Ali, a seasoned local guide, through the breathtaking juniper forests of Asir National Park. This moderate-level hike will take you to panoramic viewpoints, through ancient terraced farms, and to a hidden village where you'll share tea with locals. Learn about the unique flora and fauna of the region.",
    image: 'https://placehold.co/600x400',
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    aiHint: 'mountain hiking',
    host: users[0],
    location: 'Asir National Park',
    price: 120,
    rating: 5.0,
    reviewsCount: 58,
    availability: 'Daily at 8am',
    category: 'Adventure',
    whatYoullDo: ['Hike through scenic mountain trails', 'Visit a traditional Asiri village', 'Learn about local plants and wildlife'],
    whatIsIncluded: ['Professional guide', 'Transportation', 'Snacks and water', 'Park entry fees'],
     reviews: [reviews[3]]
  },
  {
    id: 'exp-4',
    name: 'Honey Harvesting Experience',
    description: 'Visit a local apiary and learn about the famous Asiri honey.',
    longDescription: 'Join Noura at her family apiary to discover the world of beekeeping and honey production in Asir. You will get to wear a beekeeper suit, inspect the hives, and learn about the different types of flowers that give Asiri honey its unique flavor. The experience concludes with a tasting session of various honeys.',
    image: 'https://placehold.co/600x400',
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    aiHint: 'honey apiary',
    host: users[3],
    location: 'Al-Namas',
    price: 60,
    rating: 4.9,
    reviewsCount: 29,
    availability: 'Weekends at 11am',
    category: 'Nature',
    whatYoullDo: ['Learn about beekeeping in Asir', 'Safely observe bee hives up close', 'Taste a variety of local honeys'],
    whatIsIncluded: ['Protective beekeeper suit', 'Guided tour of the apiary', 'Honey tasting session'],
    reviews: []
  },
  {
    id: 'exp-5',
    name: 'A Journey Through Rijal Almaa\'s History',
    description: 'A guided tour of the historic stone village of Rijal Almaa.',
    longDescription: 'Walk through the corridors of time with a historian guide in the stunning village of Rijal Almaa. You will explore the unique architecture of the stone fortresses, visit the local museum, and hear stories of the village\'s rich history as a regional trade center. This tour provides deep insights into the heritage of the Asir region.',
    image: 'https://placehold.co/600x400',
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    aiHint: 'historic village',
    host: users[4],
    location: 'Rijal Almaa',
    price: 50,
    rating: 4.8,
    reviewsCount: 61,
    availability: 'Tue, Thu, Sat at 9am',
    category: 'History',
    whatYoullDo: ['Explore the ancient alleyways and buildings', 'Visit the Rijal Almaa museum', 'Learn about the history and culture of the village'],
    whatIsIncluded: ['Expert historical guide', 'Museum entrance fee', 'Arabic coffee and dates'],
    reviews: []
  },
  {
    id: 'exp-6',
    name: 'Asiri Flower Crown (Mekhlab) Making',
    description: 'Create your own beautiful and fragrant Asiri flower crown.',
    longDescription: "Sit with Layla in her garden and learn the delicate art of making a Mekhlab, the traditional flower crown worn by men and women in Asir. You'll select from a variety of fresh, fragrant flowers and herbs like marigold, jasmine, and basil, and weave them into a beautiful crown to wear and take with you.",
    image: 'https://placehold.co/600x400',
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    aiHint: 'flower crown',
    host: users[5],
    location: 'Abha, Asir',
    price: 45,
    rating: 4.9,
    reviewsCount: 33,
    availability: 'Daily at 3pm',
    category: 'Culture',
    whatYoullDo: ['Learn about the tradition of flower crowns in Asir', 'Choose your own fresh flowers and herbs', 'Weave your own fragrant Mekhlab'],
    whatIsIncluded: ['All fresh flowers and materials', 'Guidance from a local expert', 'A refreshing herbal tea'],
    reviews: []
  },
];

export const conversations: Conversation[] = [
  {
    id: 'conv-1',
    participant: users[1],
    lastMessage: "Thank you! I'm looking forward to it.",
    lastMessageTimestamp: '10:42 AM',
    messages: [
      { id: 'msg-1-1', sender: 'participant', text: 'Hello! I have a question about the cooking class. Are vegetarian options available?', timestamp: '9:15 AM' },
      { id: 'msg-1-2', sender: 'user', text: 'Hi there! Absolutely, we can tailor the menu to be fully vegetarian. Just let me know when you book.', timestamp: '9:17 AM' },
      { id: 'msg-1-3', sender: 'participant', text: "That's wonderful! Thank you! I'm looking forward to it.", timestamp: '10:42 AM' },
    ],
  },
  {
    id: 'conv-2',
    participant: users[0],
    lastMessage: 'Perfect, see you then!',
    lastMessageTimestamp: 'Yesterday',
     messages: [
      { id: 'msg-2-1', sender: 'participant', text: 'Hi Ali, I booked the hike for next Friday. Just confirming the meeting point.', timestamp: 'Yesterday' },
      { id: 'msg-2-2', sender: 'user', text: 'Hi! Yes, we will meet at the entrance of Asir National Park at 8am. I will send you a precise location pin the day before.', timestamp: 'Yesterday' },
      { id: 'msg-2-3', sender: 'participant', text: 'Perfect, see you then!', timestamp: 'Yesterday' },
    ],
  },
  {
    id: 'conv-3',
    participant: users[4],
    lastMessage: 'It was a pleasure to host you.',
    lastMessageTimestamp: '3 days ago',
     messages: [
      { id: 'msg-3-1', sender: 'user', text: 'Thank you for the amazing art workshop. I learned so much!', timestamp: '3 days ago' },
      { id: 'msg-3-2', sender: 'participant', text: 'You are very welcome! It was a pleasure to host you.', timestamp: '3 days ago' },
    ],
  },
];
